"""empty message

Revision ID: 07950b032eb7
Revises: 5aef83a8a42f
Create Date: 2022-11-18 23:40:33.130706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07950b032eb7'
down_revision = '5aef83a8a42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('owner',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('owner',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
