"""empty message

Revision ID: 1da93403ba52
Revises: aa81b5d5ae0f
Create Date: 2022-11-20 11:44:37.737612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da93403ba52'
down_revision = 'aa81b5d5ae0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duels', schema=None) as batch_op:
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
