"""empty message

Revision ID: 57b47e18fdab
Revises: 370968e335df
Create Date: 2022-11-19 20:40:22.680225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b47e18fdab'
down_revision = '370968e335df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endurance_koef', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('strength_koef', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('agility_koef', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('defence_koef', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wisdom_koef', sa.Float(), nullable=True))

    with op.batch_alter_table('character_races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endurance_koef', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('strength_koef', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('agility_koef', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('defence_koef', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wisdom_koef', sa.Float(), nullable=True))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endurance_base', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('strength_base', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agility_base', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('defence_base', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wisdom_base', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('wisdom_base')
        batch_op.drop_column('defence_base')
        batch_op.drop_column('agility_base')
        batch_op.drop_column('strength_base')
        batch_op.drop_column('endurance_base')

    with op.batch_alter_table('character_races', schema=None) as batch_op:
        batch_op.drop_column('wisdom_koef')
        batch_op.drop_column('defence_koef')
        batch_op.drop_column('agility_koef')
        batch_op.drop_column('strength_koef')
        batch_op.drop_column('endurance_koef')

    with op.batch_alter_table('character_classes', schema=None) as batch_op:
        batch_op.drop_column('wisdom_koef')
        batch_op.drop_column('defence_koef')
        batch_op.drop_column('agility_koef')
        batch_op.drop_column('strength_koef')
        batch_op.drop_column('endurance_koef')

    # ### end Alembic commands ###
