"""empty message

Revision ID: 5aef83a8a42f
Revises: 4126152c5668
Create Date: 2022-11-18 19:18:39.496655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5aef83a8a42f'
down_revision = '4126152c5668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('owner',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('character_race',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('character_class',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('character_class',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('character_race',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('owner',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
